### ISSUE TITLE
windows + structor + material ui

### ISSUE THREAD

**Issue by jeffallen6767** [ipselon/structor#56] opened 2016-04-26 00:04 UTC
Hi,

  I've been following your project structor ( since it was "react-ui-builder" ) and really like it, I think you're doing great work, but now that I'm trying the latest version, I'm having an issue:

  I'm on windows 8.1 if that matters, and using chrome browser.

  I've tried the 2 different ways ( listed here: https://github.com/ipselon/structor ) to install material ui for structor, and I've even tried to npm uninstall structor and npm install -g structor again to make sure I have the latest, and still I get the same error.

GET http://localhost:2222/structor-dev/\_\_build\_\_/bundle.js  results in a 404 error

I'm attaching a screenshot showing the network tab in chrome dev tools.

Thanks for any help! Love the project!

![structor-material-ui-install](https://cloud.githubusercontent.com/assets/1063272/14802646/61fc9f58-0b07-11e6-9290-08f943c8bd59.png)

**Comment by ipselon** [comment] 2016-04-26 05:53
hi @jeffallen6767 it seems that some parts of old Structor remain in the system. So, try to uninstall completely: `npm uninstall structor -g` and then try to find a folder `structor` somewhere in nodejs home (for example on mac os it is here `NODE_HOME/lib/node_modules/structor`). And if there is that directory - just delete it.

**Comment by jeffallen6767** [comment] 2016-04-26 23:37
I did the following:
npm uninstall structor -g
searched for and removed all references to "structor" on my harddrive
npm install -g structor
tried again to install structor-material-ui 2 different ways as directed
both ways give same error as above...

**Comment by ipselon** [comment] 2016-04-27 08:30
I added babel-core dependency, please reinstall npm deps in your project. Hope it helps.

**Comment by tallaxes** [comment] 2016-04-29 00:07
Same here, 404 on /structor-dev/__build__/bundle.js

**Comment by ipselon** [comment] 2016-04-29 06:40
@tallaxes there is such an URL /structor-dev/build/bundle.js

Please try to completely uninstall Structor, and only then install in global scope, and then try to the second way for downloading a project:

1. download from market
2. unpack somewhere
3. change dir to appeared directory
4. run `npm install`
5. run `structor`

**Comment by tallaxes** [comment] 2016-04-30 00:25
Tried all of these, still the same problem.
The market download currently has a slightly outdated version of material ui pack, but cloning it from the repository did not help either.
Let me know if there is anything else I can do help troubleshoot this.

**Comment by vincealdrin** [comment] 2016-05-03 13:24
I'm having the same problem too on windows 10

**Comment by Dmytro-Medzatiy** [comment] 2016-05-03 13:37
@vincealdrin @jeffallen6767  @tallaxes  What version of npm and node are you using? 
And don't forget, you have to run Structor in "cmd" with admin rights.

**Comment by damienwebdev** [comment] 2016-05-04 01:50
I'm having a similar problem. I installed as per the README instructions and am getting: 

 "Page loading is timed out. Look at the console output and try to fix error. Page will be reloaded automatically after successful compiling."

But have a 

Structor is ready to work
Open address: http://localhost:2222/structor in the browser.
webpack built f2152897edd040019b06 in 9118ms

In my console

**Comment by vincealdrin** [comment] 2016-05-04 04:42
@Dmytro-Medzatiy node 6.0.0 and npm 3.8.6

**Comment by ipselon** [comment] 2016-05-04 08:42
@vincealdrin @damienwebdev @tallaxes @jeffallen6767 one more question: did you try another project from market? for example, bootstrap-prepack?

**Comment by yuriolive** [comment] 2016-05-10 17:36
Same here: 
- Windows 10
- node 5.0.0
- npm 3.8.9

**bootstrap-prepack** works without any problems.

**Comment by ipselon** [comment] 2016-05-10 18:44
@yuriolive could you elaborate what is exactly the same? Does "timeout error" occur? 

Also, please look at the video where the same material-ui-prepack project is installed on Cloud9 environment: https://www.youtube.com/watch?v=WCwXR31V0PA

**Comment by ipselon** [comment] 2016-05-22 09:24
Try install new version of Structor.

**Comment by Daneaux** [comment] 2016-05-24 21:33
Same issue with material prepack (0bcfdb6), tried nodejs 5.x and 6.x.  Windows 10.

Tried most recent bootstrap prepack and got a bunch of lodash errors...

**Comment by Daneaux** [comment] 2016-05-24 21:43
I get a 404 trying the starter prepack as well:
NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - http://localhost:2222/structor-dev/__build__/bundle.js

I'm using the most recent version of structor (npm install structor -g), unzipped <pick a package>, npm install in that directory, then ran 'structor', then went to localhost:2222  ... 

Not sure what I'm missing, any help would be appreciated, I'm really excited about the idea of structor.  Wish there was a hosted version I can play with.

Dan

**Comment by ipselon** [comment] 2016-05-24 21:48
@Daneaux if you are using the latest version of Structor, try to run Structor with option `-v` it will give you the ability to see what is happening while webpack is trying to compile and expose endpoint.

**Comment by ipselon** [comment] 2016-05-24 21:58
@Daneaux if you want to play with Structor :-) you may run in online on Cloud9 platform. Here is a video how to setup Structor with any of its existing projects: https://www.youtube.com/watch?v=WCwXR31V0PA

As for your local installation, try to completely uninstall Structor:
```
npm unistall structor -g
```
then install it
```
npm install structor -g
```

**Comment by Daneaux** [comment] 2016-05-24 22:01
Hi Ipselon, already installed and uninstalled and installed, but can try again :-)

Here's what I get with -v (lots and lots of other stuff, but here are the errors at the end):

ERROR in ./~/lodash/lodash.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../AppData/Roaming/npm/node_modules/structor/node_modules/webpack/buildin/module.js in C:/Users/Danny/src/structor/ipselon-structor-starter-prepack-2904859/node_modules\lodash
 @ ./~/lodash/lodash.js 1:0-108

ERROR in ./~/babel-runtime/regenerator/runtime.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../../AppData/Roaming/npm/node_modules/structor/node_modules/webpack/buildin/module.js in C:/Users/Danny/src/structor/ipselon-structor-starter-prepack-2904859/node_modules\babel-runtime\regenerator
 @ ./~/babel-runtime/regenerator/runtime.js 1:0-111

ERROR in ./~/lodash/_root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../AppData/Roaming/npm/node_modules/structor/node_modules/webpack/buildin/module.js in C:/Users/Danny/src/structor/ipselon-structor-starter-prepack-2904859/node_modules\lodash
 @ ./~/lodash/_root.js 1:0-108
webpack: bundle is now VALID.

**Comment by ipselon** [comment] 2016-05-24 22:07
@Daneaux now it's clear that somehow in your project does not have `babel-runtime` lib. Please install it manually in project node_modules:
```
npm install babel-runtime
```
then start Structor again.

**Comment by Daneaux** [comment] 2016-05-24 22:14
Babel-runtime is installed, I think it's having issues with the path "./../../../../../AppData/....."  ?

Regardless shouldn't npm install install all the dependencies (including babel) ?

I'm going to try cloud9 next.

**Comment by jaco-botha** [comment] 2016-05-25 17:39
Hi there,

Trying to install on Windows 10 but not having a lot of joy. When I did "npm install structor" I had a spinner for a very long time and no activity. FWIW my npm version is 2.15.1 
I eventually interrupted the process and repeated the install command - it then completed.
I then followed the github clone method and again got a spinner that never completed when I did "npm install" in the appeared folder. Once again I interrupted after about ten minutes and the second try completed.
I was now able to connect using web browser but the page never completed loading.

I can send a more complete error report, but I think the issue is that the installs do not complete on Windows 10. Is there a solution to this ?

Can I try a previous version that has been successfully tested on Windows 10 ?

Really hoping to try out the software - it looks very promising.

**Comment by gehad-shaat** [comment] 2016-05-26 03:46
I have the same issue one windows 10. I tried different versions of node but nothing worked.
Webpack configuration:
{
    "devtool": "inline-source-map",
    "plugins": [
        {},
        {},
        {}
    ],
    "module": {
        "loaders": [
            {
                "test": {},
                "exclude": {},
                "loader": "babel",
                "query": {
                    "cacheDirectory": true,
                    "presets": [
                        "react-hmre"
                    ],
                    "plugins": [
                        "babel-plugin-add-module-exports"
                    ]
                }
            },
            {
                "test": {},
                "exclude": {},
                "loader": "style-loader!css-loader"
            },
            {
                "test": {},
                "exclude": {},
                "loader": "url-loader"
            }
        ],
        "unknownContextRequest": ".",
        "unknownContextRecursive": true,
        "unknownContextRegExp": {},
        "unknownContextCritical": true,
        "exprContextRequest": ".",
        "exprContextRegExp": {},
        "exprContextRecursive": true,
        "exprContextCritical": true,
        "wrappedContextRegExp": {},
        "wrappedContextRecursive": true,
        "wrappedContextCritical": false
    },
    "resolve": {
        "root": [
            "C:/personal/structor_samples/structor-starter-prepack/node_modules",
            "C:/Users/ShaatDell/AppData/Roaming/npm/node_modules/structor/node_modules"
        ],
        "fastUnsafe": [],
        "alias": {},
        "packageAlias": "browser",
        "modulesDirectories": [
            "web_modules",
            "node_modules"
        ],
        "packageMains": [
            "webpack",
            "browser",
            "web",
            "browserify",
            [
                "jam",
                "main"
            ],
            "main"
        ],
        "extensions": [
            "",
            ".webpack.js",
            ".web.js",
            ".js",
            ".json"
        ]
    },
    "externals": {
        "jquery": "jQuery"
    },
    "entry": [
        "webpack-hot-middleware/client?path=/structor-dev/a&overlay=false",
        "C:/personal/structor_samples/structor-starter-prepack/.structor/src/default.js"
    ],
    "output": {
        "path": "C:\\personal\\structor_samples\\structor-starter-prepack\\.structor\\desk\\__build__",
        "filename": "bundle.js",
        "publicPath": "/structor-dev/__build__",
        "libraryTarget": "var",
        "sourceMapFilename": "[file].map[query]",
        "hotUpdateChunkFilename": "[id].[hash].hot-update.js",
        "hotUpdateMainFilename": "[hash].hot-update.json",
        "crossOriginLoading": false,
        "hashFunction": "md5",
        "hashDigest": "hex",
        "hashDigestLength": 20,
        "sourcePrefix": "\t",
        "devtoolLineToLine": false
    },
    "debug": false,
    "cache": true,
    "context": "C:\\personal\\structor_samples\\structor-starter-prepack",
    "target": "web",
    "node": {
        "console": false,
        "process": true,
        "global": true,
        "setImmediate": true,
        "__filename": "mock",
        "__dirname": "mock"
    },
    "resolveLoader": {
        "fastUnsafe": [],
        "alias": {},
        "modulesDirectories": [
            "web_loaders",
            "web_modules",
            "node_loaders",
            "node_modules"
        ],
        "packageMains": [
            "webpackLoader",
            "webLoader",
            "loader",
            "main"
        ],
        "extensions": [
            "",
            ".webpack-loader.js",
            ".web-loader.js",
            ".loader.js",
            ".js"
        ],
        "moduleTemplates": [
            "*-webpack-loader",
            "*-web-loader",
            "*-loader",
            "*"
        ]
    },
    "optimize": {
        "occurenceOrderPreferEntry": true
    }
}
Structor is ready to work
Open address: http://localhost:2222/structor in the browser.
webpack built 0b7cf2a8f41d41c87bd1 in 2652ms
Hash: 0b7cf2a8f41d41c87bd1
Version: webpack 1.12.14
Time: 2652ms
    Asset     Size  Chunks       Chunk Names
bundle.js  7.68 MB       0       main
chunk    {0} bundle.js (main) 2.95 MB [rendered]
    [0] multi main 40 bytes {0} [built]
[Truncated....]
  [553] ./src/client/assets/fonts/fontawesome-webfont.woff?v=4.4.0 108 kB {0} [built]

ERROR in ./~/lodash/lodash.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../Users/ShaatDell/AppData/Roaming/npm/node_modules/structor/node_modules/webpack/buildin/module.js in C:/personal/structor_samples/structor-starter-prepack/node_modules\lodash
 @ ./~/lodash/lodash.js 1:0-124

ERROR in ./~/babel-runtime/regenerator/runtime.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../../Users/ShaatDell/AppData/Roaming/npm/node_modules/structor/node_modules/webpack/buildin/module.js in C:/personal/structor_samples/structor-starter-prepack/node_modules\babel-runtime\regenerator
 @ ./~/babel-runtime/regenerator/runtime.js 1:0-127

ERROR in ./~/lodash/_root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../Users/ShaatDell/AppData/Roaming/npm/node_modules/structor/node_modules/webpack/buildin/module.js in C:/personal/structor_samples/structor-starter-prepack/node_modules\lodash
 @ ./~/lodash/_root.js 1:0-124
webpack: bundle is now VALID.

**Comment by gehad-shaat** [comment] 2016-05-26 03:51
I am having the same issue on Windows 10, I tried uninstalling, different versions of node, cygwin, git bash but nothing worked.

I also tried cloud9 and that didn't work either.
Fetch API cannot load https://c9users.io/_user_content/authorize?redirect=http%3A%2F%2Fmaterial-ui-gehad3003.c9users.io%3A8080%2Fstructor-project-download. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://material-ui-gehad3003.c9users.io:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Here is what I get when I do:
structor -v
Webpack configuration:
{
    "devtool": "inline-source-map",
    "plugins": [
        {},
        {},
        {}
    ],
    "module": {
        "loaders": [
            {
                "test": {},
                "exclude": {},
                "loader": "babel",
                "query": {
                    "cacheDirectory": true,
                    "presets": [
                        "react-hmre"
                    ],
                    "plugins": [
                        "babel-plugin-add-module-exports"
                    ]
                }
            },
            {
                "test": {},
                "exclude": {},
                "loader": "style-loader!css-loader"
            },
            {
                "test": {},
                "exclude": {},
                "loader": "url-loader"
            }
        ],
        "unknownContextRequest": ".",
        "unknownContextRecursive": true,
        "unknownContextRegExp": {},
        "unknownContextCritical": true,
        "exprContextRequest": ".",
        "exprContextRegExp": {},
        "exprContextRecursive": true,
        "exprContextCritical": true,
        "wrappedContextRegExp": {},
        "wrappedContextRecursive": true,
        "wrappedContextCritical": false
    },
    "resolve": {
        "root": [
            "C:/personal/structor_samples/structor-starter-prepack/node_modules",
            "C:/Users/ShaatDell/AppData/Roaming/npm/node_modules/structor/node_modules"
        ],
        "fastUnsafe": [],
        "alias": {},
        "packageAlias": "browser",
        "modulesDirectories": [
            "web_modules",
            "node_modules"
        ],
        "packageMains": [
            "webpack",
            "browser",
            "web",
            "browserify",
            [
                "jam",
                "main"
            ],
            "main"
        ],
        "extensions": [
            "",
            ".webpack.js",
            ".web.js",
            ".js",
            ".json"
        ]
    },
    "externals": {
        "jquery": "jQuery"
    },
    "entry": [
        "webpack-hot-middleware/client?path=/structor-dev/a&overlay=false",
        "C:/personal/structor_samples/structor-starter-prepack/.structor/src/default.js"
    ],
    "output": {
        "path": "C:\\personal\\structor_samples\\structor-starter-prepack\\.structor\\desk\\__build__",
        "filename": "bundle.js",
        "publicPath": "/structor-dev/__build__",
        "libraryTarget": "var",
        "sourceMapFilename": "[file].map[query]",
        "hotUpdateChunkFilename": "[id].[hash].hot-update.js",
        "hotUpdateMainFilename": "[hash].hot-update.json",
        "crossOriginLoading": false,
        "hashFunction": "md5",
        "hashDigest": "hex",
        "hashDigestLength": 20,
        "sourcePrefix": "\t",
        "devtoolLineToLine": false
    },
    "debug": false,
    "cache": true,
    "context": "C:\\personal\\structor_samples\\structor-starter-prepack",
    "target": "web",
    "node": {
        "console": false,
        "process": true,
        "global": true,
        "setImmediate": true,
        "__filename": "mock",
        "__dirname": "mock"
    },
    "resolveLoader": {
        "fastUnsafe": [],
        "alias": {},
        "modulesDirectories": [
            "web_loaders",
            "web_modules",
            "node_loaders",
            "node_modules"
        ],
        "packageMains": [
            "webpackLoader",
            "webLoader",
            "loader",
            "main"
        ],
        "extensions": [
            "",
            ".webpack-loader.js",
            ".web-loader.js",
            ".loader.js",
            ".js"
        ],
        "moduleTemplates": [
            "*-webpack-loader",
            "*-web-loader",
            "*-loader",
            "*"
        ]
    },
    "optimize": {
        "occurenceOrderPreferEntry": true
    }
}
Structor is ready to work
Open address: http://localhost:2222/structor in the browser.
webpack built 0b7cf2a8f41d41c87bd1 in 2652ms
Hash: 0b7cf2a8f41d41c87bd1
Version: webpack 1.12.14
Time: 2652ms
    Asset     Size  Chunks       Chunk Names
bundle.js  7.68 MB       0       main
chunk    {0} bundle.js (main) 2.95 MB [rendered]
    [0] multi main 40 bytes {0} [built]
[TRUNCATED....]
  [553] ./src/client/assets/fonts/fontawesome-webfont.woff?v=4.4.0 108 kB {0} [built]

ERROR in ./~/lodash/lodash.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../Users/ShaatDell/AppData/Roaming/npm/node_modules/structor/node_modules/webpack/buildin/module.js in C:/personal/structor_samples/structor-starter-prepack/node_modules\lodash
 @ ./~/lodash/lodash.js 1:0-124

ERROR in ./~/babel-runtime/regenerator/runtime.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../../Users/ShaatDell/AppData/Roaming/npm/node_modules/structor/node_modules/webpack/buildin/module.js in C:/personal/structor_samples/structor-starter-prepack/node_modules\babel-runtime\regenerator
 @ ./~/babel-runtime/regenerator/runtime.js 1:0-127

ERROR in ./~/lodash/_root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../../../Users/ShaatDell/AppData/Roaming/npm/node_modules/structor/node_modules/webpack/buildin/module.js in C:/personal/structor_samples/structor-starter-prepack/node_modules\lodash
 @ ./~/lodash/_root.js 1:0-124
webpack: bundle is now VALID.

**Comment by ipselon** [comment] 2016-05-26 09:31
@gehad-shaat as for cloud9, you might missed some steps from video tutorials, because it can not be that one installation failed when all others succeed. 

Regarding local installation on Windows 10, I think that the problem is in how windows interprets a long path, for example: `./~/babel-runtime/regenerator/runtime.js`

So, I want to propose to try the following:

* uninstall Structor from global space: `nmp uninstall structor -g`
* install Structor locally (`npm install structor`) in some empty dir which is not so deep by path: `c:\test\test`
* copy the following package.json file into that folder:
```json
{
  "name": "testing",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "structor -d <absolute path to your project>",
  },
  "author": "",
  "license": "ISC"
}
```
* change `<absolute path to your project>` with your path where material-ui-prepack is.
* run in command line: `npm run start`

**Comment by gehad-shaat** [comment] 2016-05-26 14:25
@ipselon the error is no limited to babel

ERROR in The node API for `babel` has been moved to `babel-core`.
 @ multi main
webpack: bundle is now VALID.

but I still get this error in the browser
GET http://localhost:2222/structor-dev/__build__/bundle.js home:18

**Comment by gehad-shaat** [comment] 2016-05-26 14:56
@ipselon in regards to cloud9
I get the following error in the browser:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://c9users.io/_user_content/authorize?redirect=http%3A%2F%2Fstructor-MyUser.c9users.io%3A8080%2Fstructor-project-download. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

If I enable CORS from browser, I get this error:
Obtaining project status error. Cannot read property 'error' of undefined

**Comment by changero** [comment] 2016-06-01 05:52
ERROR in ./.structor/src/PageForDesk.js
Module not found: Error: Cannot resolve 'file' or 'directory' D:\Documents\project\material-ui-prepack-m
aster\node_modules\babel-preset-react-hmre\node_modules\redbox-react\lib\index.js
in D:\Documents\project\material-ui-prepack-master\.structor\src
 @ ./.structor/src/PageForDesk.js 35:13-156

**Comment by strongui** [comment] 2016-06-02 13:51
Having same issue on windows 10. Tried everything in this post, but continue to get : 
http://localhost:2222/structor-dev/__build__/bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by theanthonyplan** [comment] 2016-06-08 08:33
I too have been experiencing these issues.  I am running windows 10, but I have also been experiencing an issue on my ubuntu machines where localhost:2222/structor yields an error that says "Projects gallery loading error. Error connection to https://helmetrex.com/sm/public/gallery/list".

Still working on finding a fix, but so far no luck.  Thanks for your help

**Comment by bugport** [comment] 2016-06-08 14:31
@theanthonyplan @strongui @Daneaux @jaco-botha @ipselon Maybe you have to try Docker way  https://hub.docker.com/r/bugport/structor/

**Comment by theanthonyplan** [comment] 2016-06-09 07:31
@bugport Thank you so much, that docker image solved all my problems.  If its not a regular thing already, I would implore you to consider continuing to make these images for future structor releases. 

I'm not that familiar with docker so I am not sure how much work it took to publish that image, but it looks like it is something worth learning.  If its the case that neither you nor @ipselon have the time to publish docker images for each major release, then perhaps I can take up the responsibility.  It just made deployment so blazingly fast and simple that I think it might have a real impact on getting structor into the hands of the people who need it.

If you could point me in the direction of whatever docs that are pertinent to preparing such an image, I would be greatly appreciative.  Thanks again guys!

**Comment by alexlukin-softgrad** [comment] 2016-06-13 11:56
Have the same issue with the latest version of Structor.

Completely uninstall the previous version of Structor, then install the latest one. Then copy and unpack bootstrap-prepack from helmetrex.com as described in ReadMe (preferable way for Windows users).
In browser console I have this error

http://localhost:2222/structor-dev/\__build\__/bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)

Structor v. 0.2.9 works for me. So, I downgrade to this version until the above error won't be fixed.

**Comment by ipselon** [comment] 2016-06-13 13:44
@alexlukin-softgrad Could you try to start Structor v1.0.10 with `-v` option in command line? Running with this option Structor prints additional info.

**Comment by alexlukin-softgrad** [comment] 2016-06-14 07:24
@ipselon Yes, sure. You can find this logs in attached file.
[structor_logs.txt](https://github.com/ipselon/structor/files/313332/structor_logs.txt)

**Comment by ipselon** [comment] 2016-06-14 08:16
@alexlukin-softgrad, @bugport, @strongui, @theanthonyplan, @gehad-shaat, @jaco-botha, @Daneaux, @yuriolive, @vincealdrin, @tallaxes, @jeffallen6767 it seems that I found a resolution for running Structor on Windows machines.

I provided some investigation, and it appeared that there are some problems with paths in node.js environment on Windows OS.

So, in order to overcome this issue you can try to install and run Structor locally. Please follow the instruction below:

* Uninstall completely Structor if you have it installed globally
* Clone or download a project manually, and then install deps as it is described in Readme
* Being in the project's folder install Structor locally: 

```
npm install structor
```
* Add the following line into `package.json` scripts section:

```
"scripts": {
  ...
  "structor": "structor"
  ...
}
```

* Run Structor: 

```
npm run structor
```

**Comment by alexlukin-softgrad** [comment] 2016-06-14 11:40
@ipselon Yes, it works. Thanks a lot!

**Comment by jaco-botha** [comment] 2016-06-16 11:57
Thanks for the instructions, It worked for me also!

**Comment by tpfennig** [comment] 2016-07-02 10:52
Hello,
i do have same problem with paths:
i did install localy, like in post above, but i get error on page:

./~/structor/~/webpack-hot-middleware/client.js?path=/structor-dev/a&overlay=false Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../webpack/buildin/module.js in c:/hoffmann/node_modules/structor/node_modules\webpack-hot-middleware resolve file 
c:/hoffmann/node_modules/structor/node_modules\webpack\buildin\module.js doesn't exists
c:/hoffmann/node_modules/structor/node_modules\webpack\buildin\module.js.webpack.js doesn't exists
....
Windows 10 pro
nodejs 4.4.6
npm 2.15.5

Thanks

**Comment by ipselon** [comment] 2016-09-03 14:40
I'll close this issue - taking in account new version of Structor is installed locally inside of React Boilerplate project, there should not be any issues with paths.

**Closed by ipselon** 2016-09-03 14:40 UTC
